### ISSUE TITLE
Confusing semantics of XOR

### ISSUE THREAD

**Issue by reteprelief** [saeaadl/emv2#27] opened 2016-10-04 11:32 UTC
Example:
A1 XOR A2 XOR A3
In Boolean logic A1 T A2 T A3 T results in T
Intuitively users may expect multi-operand XOR semantics, i.e., only one of A1,A2,A3 is true

Proposal: k **of** ( A1,A2,A3)
follows **ormore** style.

**Comment by buzden** [comment] 2016-10-04 22:07
Which expressions is this issue related to?

XOR implies a logical negation which is not present in FTA (as is was discussed in #15).

**Comment by lwrage** [comment] 2016-12-06 17:53
This is a duplicate of #6

**Closed by lwrage** 2016-12-06 17:53 UTC
